### ISSUE TITLE
some write error in code

### ISSUE THREAD

**Issue by yuantangjin** [rubensamarojr/polymps#2]
https://github.com/rubensamarojr/polymps/blob/16362ea969d79c0a9cceb97260005ad0f521420f/src/MpsParticle.cpp#L988
I think some wrong have happened here, it may be like following:
` limDom[2][0] -= 0.5*partDist;	limDom[2][1] += 0.5*partDist; `

**Comment by rubensamarojr** [comment]
Hi @yuantangjin 

You are right, thank you. I'll fix this bug.

**Comment by yuantangjin** [comment]
Glad to be able to help. This code is excellent, I'm still trying to learn more!
