### ISSUE TITLE
A problem about checkParticleOutDomain()

### ISSUE THREAD

**Issue by yuantangjin** [rubensamarojr/polymps#3]
https://github.com/rubensamarojr/polymps/blob/fa0f3ca705e8c2023a9d3ae1ac2e2f1e2048a9f3/src/MpsParticle.cpp#L1353
I think here have some problem. It should be `vel[iLastParticle*3 + j] = 0.0; `

**Comment by rubensamarojr** [comment]
Hi,

Indeed, +j was missing. I'll fix that. Thanks!
